"""Tests for Discord thread starter-name hygiene.

When a user manually creates a thread off a Hermes message and posts in it,
Hermes must not rename that thread from the raw first user message. Visible
thread names should follow the Hermes session title generated by
``agent.title_generator.maybe_auto_title`` and propagated through the gateway's
Discord title callback.
"""

import asyncio
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock
import pytest

from tests.gateway.test_discord_send import _ensure_discord_mock

_ensure_discord_mock()

import plugins.platforms.discord.adapter as discord_adapter  # noqa: E402
from plugins.platforms.discord.adapter import DiscordAdapter  # noqa: E402
from gateway.config import PlatformConfig  # noqa: E402


def _adapter():
    adapter = DiscordAdapter(PlatformConfig(enabled=True, token="***"))
    # Replace the persistent tracker with a plain set so tests never touch the
    # real ~/.hermes/discord_threads.json. The method under test only reads
    # membership via ``in``; participation marking happens at the call site.
    adapter._threads = set()
    return adapter


class TestDeriveThreadName:
    def test_strips_mentions_and_collapses_whitespace(self):
        adapter = _adapter()
        assert adapter._derive_thread_name("  <@123>  hello   world ") == "hello world"

    def test_truncates_to_80_with_ellipsis(self):
        adapter = _adapter()
        name = adapter._derive_thread_name("x" * 100)
        assert len(name) == 80
        assert name.endswith("...")

    def test_empty_after_stripping_returns_empty(self):
        adapter = _adapter()
        assert adapter._derive_thread_name("   <@123> <#456> ") == ""


class TestResolveThreadParent:
    def test_prefers_hydrated_parent(self):
        adapter = _adapter()
        parent = object()
        channel = SimpleNamespace(parent=parent, parent_id=999)
        assert adapter._resolve_thread_parent(channel) is parent

    def test_falls_back_to_parent_id_cache_lookup(self):
        adapter = _adapter()
        forum = object()
        adapter._client = SimpleNamespace(get_channel=lambda cid: forum if cid == 999 else None)
        channel = SimpleNamespace(parent=None, parent_id=999)
        assert adapter._resolve_thread_parent(channel) is forum

    def test_returns_channel_when_no_parent_resolvable(self):
        adapter = _adapter()
        adapter._client = SimpleNamespace(get_channel=lambda cid: None)
        channel = SimpleNamespace(parent=None, parent_id=None)
        assert adapter._resolve_thread_parent(channel) is channel


class _Tracker:
    def __init__(self):
        self.marked = set()

    def __contains__(self, thread_id):
        return thread_id in self.marked

    def mark(self, thread_id):
        self.marked.add(thread_id)


@pytest.mark.asyncio
async def test_fresh_user_thread_is_not_renamed_from_first_message(monkeypatch):
    """Fresh user-created threads wait for session-title sync, not raw text."""
    class FakeThread:
        def __init__(self):
            self.id = 800
            self.parent_id = 700
            self.parent = SimpleNamespace(id=700, type=0)

    monkeypatch.setattr(discord_adapter.discord, "Thread", FakeThread)
    monkeypatch.setenv("DISCORD_REQUIRE_MENTION", "false")
    adapter = _adapter()
    adapter._text_batch_delay_seconds = 0
    tracker = _Tracker()
    adapter._threads = tracker
    adapter._client = SimpleNamespace(user=SimpleNamespace(id=1))
    adapter._discord_history_backfill = MagicMock(return_value=False)
    adapter._resolve_channel_skills = MagicMock(return_value=None)
    adapter._resolve_channel_prompt = MagicMock(return_value=None)
    adapter.rename_thread = AsyncMock()
    adapter.handle_message = AsyncMock()

    thread = FakeThread()

    message = SimpleNamespace(
        id=900,
        content="这是我很长的第一条任务消息，不应该直接变成 thread 名字",
        mentions=[],
        attachments=[],
        message_snapshots=[],
        reference=None,
        channel=thread,
        type=object(),
        created_at=None,
        author=SimpleNamespace(id=42, display_name="tester", name="tester", bot=False),
        guild=SimpleNamespace(id=1234),
    )

    await adapter._handle_message(message)
    await asyncio.sleep(0)

    adapter.rename_thread.assert_not_awaited()
    assert "800" in tracker.marked
    adapter.handle_message.assert_awaited_once()
